api/api/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('predictor.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    #test mode
    from django.conf.urls.static import static
    # urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/predictor/urls.py
from django.urls import path
from . import views

app_name = 'predictor'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('result/',views.model_form_upload,name = 'result'),
]

api/predictor/models.py
from django.db import models
from . models import *
import joblib
# Create your models here.



class Document(models.Model):
    file = models.FileField(upload_to='file/')

#class Data(models.Model):
#    
#    
#    filename = models.FileField()
#    prediction = models.CharField(max_length=100,blank=True)
#    def save(self, *args, **kwargs):
#        models = joblib.load('models/models.sav')
#        self.prediction = models.predict(
#            [[self.filename]]
#        )
#        return super().save(*args, **kwargs)
#
#

  

  

api/predictor/forms.py
from django import forms
from .models import Document

class DocumentForm(forms.Form):
    def is_valid(*args, **kwargs):
        return True

    file = forms.FileField(help_text='Valid .mp3 file')

api/predictor/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView
from .apps import PredictorConfig
from .forms import DocumentForm
from .models import Document
from .Metadata import getmetadata
import warnings
from .predict import predict_gen

from django.contrib import messages
warnings.simplefilter('ignore')

class IndexView(ListView):
    template_name= 'babycry/index.html' #template for babycry
    def get_queryset(self):
        return True

def model_form_upload(request):

    documents = Document.objects.all()
    if request.method == 'POST':
        if len(request.FILES) == 0:
            messages.error(request,'Upload a file')
            return redirect("predictor:index")

        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            uploadfile = request.FILES['document']
            print(uploadfile.name)
            print(uploadfile.size)
            if not uploadfile.name.endswith('.wav'):
                messages.error(request,'Only .wav file type is allowed')
                return redirect("predictor:index")
            meta = getmetadata(uploadfile)
            
            genre = predict_gen(meta)
            print(genre)

            context = {'genre':genre}
            return render(request,'babycry/result.html',context)  # result page of babycry
    else:
        form = DocumentForm()

    return render(request,'babycry/result.html',{'documents':documents,'form':form})

api/predictor/templates/babycry/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>Music Genre Classification</title>
	<link rel="icon" href="#">
</head>
<body>


<div class="content">

    {% block content %}

    <!-- content for different pages here -->

    {% endblock content %}
  </div>


</body>


</html>

api/predictor/templates/babycry/check_genre.html
{% extends 'babycry/base.html' %}
{% load static %}
{% block content %}

  <div class="row">
    <form action="{% url 'predictor:result' %}" method="POST" enctype="multipart/form-data" class="up-form">
       {% csrf_token %}
       <input type="file" name='document' multiple="" class="up-input">
       {{form.as_table}}
      <p class="up-p">Drag your music file here or click in this area.</p>
      <button type="submit" class="btn btn-sm btn-success" style="margin-left: 9rem; width: 30vh;">Check</button>

    </form>
</div> <!-- end of row -->
{% endblock%}

api/predictor/templates/babycry/index.html
{% extends 'babycry/base.html' %}
{% load static %}


{% block content %}

<h1>Index home page</h1>

{% include 'babycry/check_genre.html' %}



{% endblock %}

api/predictor/templates/babycry/result.html
{{file.name}}

<html lang="en">
<head>

	<title>Music Genre Classification</title>

</head>

<body data-spy="scroll" data-target=".fixed-top">

    <i>
        {{ genre }}
    </i>
                                        

</body>
</html>